### ISSUE TITLE
dev server constantly crashing with "Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'"

### ISSUE THREAD

**Issue by mklueh** [wxt-dev/wxt#1106]
### Describe the bug

I have the feeling that this happens after a while when a few reloads have happened, and I'm not sure if it is even related to this library, as I'm facing the same with Nuxt as well. Might be Vite related, but maybe sb has the same problem and has found a workaround.

```

WXT 0.19.13
✔ Started dev server @ http://localhost:3001
ℹ Pre-rendering chrome-mv3 for development with Vite 5.4.9
- Preparing...
✔ Built extension in 5.507 s
  ├─ .output\chrome-mv3\manifest.json                1.37 kB
  ├─ .output\chrome-mv3\popup.html                   636 B
  ├─ .output\chrome-mv3\background.js                89.43 kB
  ├─ .output\chrome-mv3\chunks\popup-CMB-8dTp.js     3.1 kB
  ├─ .output\chrome-mv3\content-scripts\content.js   701.24 kB
  ├─ .output\chrome-mv3\content-scripts\content.css  2.36 kB
  ├─ .output\chrome-mv3\icon\128.png                 3.07 kB
  ├─ .output\chrome-mv3\icon\16.png                  559 B
  ├─ .output\chrome-mv3\icon\32.png                  916 B
  ├─ .output\chrome-mv3\icon\48.png                  1.33 kB
  ├─ .output\chrome-mv3\icon\96.png                  2.37 kB
  └─ .output\chrome-mv3\wxt.svg                      1.07 kB
Σ Total size: 807.45 kB
node:events:497
      throw er; // Unhandled 'error' event
      ^
Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (file:///C:/Users/MyPC/Workspace/my-project/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:44469:10)
    at ReaddirpStream.NodeFsHandler._boundHandleError (file:///C:/Users/MyPC/Workspace/my-project/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:42942:43)
    at ReaddirpStream.emit (node:events:519:28)
    at ReaddirpStream.emit (node:domain:488:12)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'lstat',
  path: 'C:\\DumpStack.log.tmp'
}
Node.js v22.9.0
```

### Reproduction

Not sure, but I have this with Nuxt too, but not with my express server

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 1.95 GB / 15.77 GB
  Binaries:
    Node: 22.9.0 - ~\AppData\Local\Volta\tools\image\node\22.9.0\node.EXE
    Yarn: 4.5.1 - ~\AppData\Local\Volta\tools\image\yarn\4.5.1\bin\yarn.CMD
    npm: 10.8.3 - ~\AppData\Local\Volta\tools\image\node\22.9.0\npm.CMD
  Browsers:
    Chrome: 130.0.6723.59
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    vite: 5.4.9 => 5.4.9 
    wxt: 0.19.13 => 0.19.13
```

### Used Package Manager

yarn

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by 1natsu172** [comment]
@mklueh I think you should submit a minimal reproduction. Can you submit it?

**Comment by aklinker1** [comment]
If it's happening with Nuxt, it's probably related to a dependency we share... Maybe Chokidar? What versions of `chokidar` are listed in your lockfile?

**Comment by mklueh** [comment]
Good point. I was on chokidar 3.6.0 before, and now I've enforced 4.0.1 but facing the same problem

**Comment by mklueh** [comment]
Haven't faced it with Nuxt anymore for a while now, but the Wxt issue remains. Are you guys developing on Windows?

**Comment by aklinker1** [comment]
I don't have a windows machine. Did Nuxt have an issue for this that got closed that we can reference?

**Comment by shaohan0228** [comment]
i developed on windows 11, my package.json

```json
{
  "name": "@downloader/plugin",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "dev": "wxt",
    "dev:firefox": "wxt -b firefox",
    "build": "wxt build",
    "build:firefox": "wxt build -b firefox",
    "zip": "wxt zip",
    "zip:firefox": "wxt zip -b firefox",
    "compile": "vue-tsc --noEmit",
    "clean": "rimraf dist",
    "postinstall": "wxt prepare"
  },
  "dependencies": {
    "@types/chrome": "^0.0.268",
    "pinia": "^2.3.0",
    "vue": "^3.5.13"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.2.1",
    "axios": "^1.7.9",
    "rimraf": "^5.0.10",
    "sass": "^1.83.0",
    "typescript": "^5.7.2",
    "unocss": "^0.60.4",
    "unplugin-icons": "^0.22.0",
    "vite": "^5.4.11",
    "vite-plugin-vue-devtools": "^7.6.8",
    "vue-tsc": "^1.8.27",
    "wxt": "^0.17.12"
  }
}
```

This is my project structure. In the entrypoints, only content is the code I actually developed. When I modify the code in content/App.vue, this issue almost always occurs, but I can't determine the exact timing or cause.

![image](https://github.com/user-attachments/assets/b726648c-bac8-4ab0-b648-ae4bd796315a)

**Comment by shaohan0228** [comment]
> i developed on windows 11, my package.json
> 
> ```json
> {
>   "name": "@downloader/plugin",
>   "private": true,
>   "version": "0.1.0",
>   "type": "module",
>   "scripts": {
>     "dev": "wxt",
>     "dev:firefox": "wxt -b firefox",
>     "build": "wxt build",
>     "build:firefox": "wxt build -b firefox",
>     "zip": "wxt zip",
>     "zip:firefox": "wxt zip -b firefox",
>     "compile": "vue-tsc --noEmit",
>     "clean": "rimraf dist",
>     "postinstall": "wxt prepare"
>   },
>   "dependencies": {
>     "@types/chrome": "^0.0.268",
>     "pinia": "^2.3.0",
>     "vue": "^3.5.13"
>   },
>   "devDependencies": {
>     "@vitejs/plugin-vue": "^5.2.1",
>     "axios": "^1.7.9",
>     "rimraf": "^5.0.10",
>     "sass": "^1.83.0",
>     "typescript": "^5.7.2",
>     "unocss": "^0.60.4",
>     "unplugin-icons": "^0.22.0",
>     "vite": "^5.4.11",
>     "vite-plugin-vue-devtools": "^7.6.8",
>     "vue-tsc": "^1.8.27",
>     "wxt": "^0.17.12"
>   }
> }
> ```
> 
> This is my project structure. In the entrypoints, only content is the code I actually developed. When I modify the code in content/App.vue, this issue almost always occurs, but I can't determine the exact timing or cause.
> 
> ![image](https://private-user-images.githubusercontent.com/9130583/399603553-b726648c-bac8-4ab0-b648-ae4bd796315a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4OTI1NjMsIm5iZiI6MTczNTg5MjI2MywicGF0aCI6Ii85MTMwNTgzLzM5OTYwMzU1My1iNzI2NjQ4Yy1iYWM4LTRhYjAtYjY0OC1hZTRiZDc5NjMxNWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDNUMDgxNzQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDhhYmE2ZDNhNmM5MDg3NDMxNTUzNzBhYjgyYWM1MjFmZGRiYjkxMmEyMzI4Zjk1ZmFhNmI4ZjVkNTVmMzRiYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.bKdVPp9eVxjpVsDjjDJDILY2eqWz0IHBzCGuhMNoaeU)

---

In my project, I suspect the issue might be related to Unocss, but the root cause could involve Vite or some deeper underlying mechanisms.

Here are relevant issues that provide some temporary solutions:

- https://github.com/dcloudio/uni-app/issues/3603
- https://github.com/crxjs/chrome-extension-tools/issues/538

## Temporary Solutions for Reference
1. Switch from Unocss to TailwindCSS.
I tested several projects based on WXT, Vite, and Unocss that I found on GitHub. All of them eventually triggered this issue after running for some time on my machine. However, when I switched from Unocss to TailwindCSS, the issue did not reappear.

2. Identify the error-causing code and skip the related errors.

```js
_handleError(error) {
  const code = error && error.code;
  if (error && code !== 'ENOENT' && code !== 'ENOTDIR' &&
    (!this.options.ignorePermissionErrors || (code !== 'EPERM' && code !== 'EACCES'))
  ) {
    const filePath = 'C:\\DumpStack.log.tmp';
    if (error.code === "EBUSY" && error.path === filePath) {
        return error;
    }
    this.emit(EV_ERROR, error);
  }
  return error || this.closed;
}
```

**Comment by aklinker1** [comment]
Gonna close this as stale without a reproduction.

**Comment by LiMao00** [comment]
It keeps interrupting the operation in my project, it's so painful.
