### ISSUE TITLE
Submit fails both stores

### ISSUE THREAD

**Issue by consciousweb** [wxt-dev/wxt#1124]
### Describe the bug

trying to use submit, and submission fails both stores. I have init both and have a .env.submit

Chrome: fails for unknown reason

Firefox: fails because it requires a string for config.manifest.content_security_policy instead of an array like Chrome v3. I used the -c param with zip and a custom firefox config and it submit correctly. Is there some way WXT has built in to handle this compatibility issue more smoothly that I'm missing?

Cli Command:
```
wxt submit \          
  --chrome-zip .output/[package]-[version]-chrome.zip \
  --firefox-zip .output/[package]-[version]-firefox.zip --firefox-sources-zip .output/[package]-[version]-sources.zip \
```

Logs:
```
ℹ Publishing Extension                                                                                     12:05:41 PM
✖ [PUT] "https://www.googleapis.com/upload/chromewebstore/v1.1/items/[chrome id]": 403 Forbidden
✖ [POST] "https://addons.mozilla.org/api/v5/addons/addon/[firefox id]/versions/": 400
  Bad Request

Request: https://www.googleapis.com/upload/chromewebstore/v1.1/items/[chrome id]
Response: {
  "_data": {
    "error": {
      "code": 403,
      "message": "Forbidden",
      "errors": [
        {
          "message": "Forbidden",
          "domain": "global",
          "reason": "forbidden"
        }
      ]
    }
  }
}
[12:05:41 PM]  ERROR  [PUT] "https://www.googleapis.com/upload/chromewebstore/v1.1/items/[id]": 403 Forbidden

  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async $fetch2 (/Users/[user]/.nvm/versions/node/v20.9.0/lib/node_modules/wxt/node_modules/ofetch/dist/shared/ofetch.d8adb063.cjs:322:15)
  at async CwsApi.uploadZip (/Users/[user]/.nvm/versions/node/v20.9.0/lib/node_modules/wxt/node_modules/publish-browser-extension/dist/cli.cjs:2920:5)
  at async ChromeWebStore.submit (/Users/[user]/.nvm/versions/node/v20.9.0/lib/node_modules/wxt/node_modules/publish-browser-extension/dist/cli.cjs:3010:5)
  at async Task.task [as taskFn] (/Users/[user]/.nvm/versions/node/v20.9.0/lib/node_modules/wxt/node_modules/publish-browser-extension/dist/cli.cjs:3511:11)
  at async Task.run (/Users/[user]/.nvm/versions/node/v20.9.0/lib/node_modules/wxt/node_modules/listr2/dist/index.cjs:2143:11)
Request: https://addons.mozilla.org/api/v5/addons/addon/[firefox id]/versions/
Response: {
  "_data": {
    "upload": [
      "Upload is not valid."
    ]
  }
}
[12:06:14 PM]  ERROR  [POST] "https://addons.mozilla.org/api/v5/addons/addon/[firefox id]/versions/": 400 Bad Request

  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async $fetch2 (/Users/[user]/.nvm/versions/node/v20.9.0/lib/node_modules/wxt/node_modules/ofetch/dist/shared/ofetch.d8adb063.cjs:322:15)
  at async AddonsApi.versionCreate (/Users/[user]/.nvm/versions/node/v20.9.0/lib/node_modules/wxt/node_modules/publish-browser-extension/dist/cli.cjs:3262:12)
  at async FirefoxAddonStore.submit (/Users/[user]/.nvm/versions/node/v20.9.0/lib/node_modules/wxt/node_modules/publish-browser-extension/dist/cli.cjs:3333:22)
  at async Task.task [as taskFn] (/Users/[user]/.nvm/versions/node/v20.9.0/lib/node_modules/wxt/node_modules/publish-browser-extension/dist/cli.cjs:3511:11)
  at async Task.run (/Users/[user]/.nvm/versions/node/v20.9.0/lib/node_modules/wxt/node_modules/listr2/dist/index.cjs:2143:11)

 ERROR  Submissions failed: 2      
```

### Reproduction

n/a

### System Info

```shell
System:
    OS: macOS 12.6.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 79.53 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.5.1 - ~/.nvm/versions/node/v20.9.0/bin/npm
    Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 130.0.6723.70
    Firefox: 131.0.3
    Safari: 15.6.1
  npmPackages:
    wxt: ^0.19.9 => 0.19.9
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
For chrome, did you create a refresh token using `wxt submit init`?

For Firefox, I think there's a bug where WXT doesn't automatically convert MV3 `content_security_policy` to it's MV2 form.

**Comment by consciousweb** [comment]
Yes and the refresh token is saved in the .env.submit

**Comment by aklinker1** [comment]
Are you using the right extension ID? Does a dry run pass? `wxt submit --dry-run`. Works fine for me, so something has to be wrong with your credentials. Did you create the gcp credentials in the same account that has access to the CWS?

**Comment by consciousweb** [comment]
Dry run runs fine. Check OP, firefox works if you specify a separate
config. Chrome does not work, cws creds are correct.

**Comment by Timeraa** [comment]
Does it work if you upload them yourself? I had an issue once with Firefox's validation that `publish` didn't show for some bizzare reason

**Comment by aklinker1** [comment]
Gonna close this since we could not reproduce.
