### ISSUE TITLE
Firefox ZIP command not working

### ISSUE THREAD

**Issue by joneslloyd** [wxt-dev/wxt#1224]
### Describe the bug

When I run `pnpm wxt zip:firefox`, I get this:
```
pnpm wxt zip:firefox

WXT 0.19.16                                                                                                                             02:00:16

 WARN  Entrypoints directory not found: ./zip:firefox/entrypoints                                                                       02:00:16

(!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.
✔ Started dev server @ http://localhost:3000                                                                                           02:00:16
ℹ Pre-rendering chrome-mv3 for development with Vite 5.4.11                                                                            02:00:16
✖ Command failed after 378 ms                                                                                                          02:00:16

[02:00:16]  ERROR  No entrypoints found in /Users/joneslloyd/Dropbox/Mac/Documents/personal/development/bluniversal-comments/packages/wxt/zip:firefox/entrypoints

  at preventNoEntrypoints (/Users/joneslloyd/Dropbox/Mac/Documents/personal/development/bluniversal-comments/node_modules/.pnpm/wxt@0.19.16_@types+node@20.17.8_rollup@4.27.4_tsx@4.19.2/node_modules/wxt/dist/core/utils/building/find-entrypoints.mjs:172:11)
  at findEntrypoints (/Users/joneslloyd/Dropbox/Mac/Documents/personal/development/bluniversal-comments/node_modules/.pnpm/wxt@0.19.16_@types+node@20.17.8_rollup@4.27.4_tsx@4.19.2/node_modules/wxt/dist/core/utils/building/find-entrypoints.mjs:51:3)
  at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  at async internalBuild (/Users/joneslloyd/Dropbox/Mac/Documents/personal/development/bluniversal-comments/node_modules/.pnpm/wxt@0.19.16_@types+node@20.17.8_rollup@4.27.4_tsx@4.19.2/node_modules/wxt/dist/core/utils/building/internal-build.mjs:30:23)
  at async buildAndOpenBrowser (/Users/joneslloyd/Dropbox/Mac/Documents/personal/development/bluniversal-comments/node_modules/.pnpm/wxt@0.19.16_@types+node@20.17.8_rollup@4.27.4_tsx@4.19.2/node_modules/wxt/dist/core/create-server.mjs:78:28)
  at async Object.start (/Users/joneslloyd/Dropbox/Mac/Documents/personal/development/bluniversal-comments/node_modules/.pnpm/wxt@0.19.16_@types+node@20.17.8_rollup@4.27.4_tsx@4.19.2/node_modules/wxt/dist/core/create-server.mjs:43:9)
  at async /Users/joneslloyd/Dropbox/Mac/Documents/personal/development/bluniversal-comments/node_modules/.pnpm/wxt@0.19.16_@types+node@20.17.8_rollup@4.27.4_tsx@4.19.2/node_modules/wxt/dist/cli/commands.mjs:32:5
  at async CAC.<anonymous> (/Users/joneslloyd/Dropbox/Mac/Documents/personal/development/bluniversal-comments/node_modules/.pnpm/wxt@0.19.16_@types+node@20.17.8_rollup@4.27.4_tsx@4.19.2/node_modules/wxt/dist/cli/cli-utils.mjs:17:22)
  at async /Users/joneslloyd/Dropbox/Mac/Documents/personal/development/bluniversal-comments/node_modules/.pnpm/wxt@0.19.16_@types+node@20.17.8_rollup@4.27.4_tsx@4.19.2/node_modules/wxt/dist/cli/index.mjs:11:1
  ```
  
What is interesting is that the directory it's looking for is `wxt/zip:firefox/entrypoints`, yet for Chrome ZIPs (`pnpm wxt zip`) I don't get this error.

### Reproduction

https://github.com/joneslloyd/bluniversal-comments/tree/main/packages/wxt
![Screenshot 2024-11-29 at 02 06 08](https://github.com/user-attachments/assets/34109665-5d7a-46d9-a10a-a7843983de34)

### Steps to reproduce

Run `pnpm wxt zip:firefox` in the `./packages/wxt/` directory.

### System Info

```shell
System:
    OS: macOS 15.1.1
    CPU: (8) arm64 Apple M2
    Memory: 102.58 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 23.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 10.9.0 - /opt/homebrew/bin/npm
    pnpm: 9.13.2 - ~/Library/pnpm/pnpm
    bun: 1.1.29 - /usr/local/bun/bin/bun
  Browsers:
    Chrome: 131.0.6778.86
    Safari: 18.1.1
  npmPackages:
    wxt: ^0.19.13 => 0.19.16
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by joneslloyd** [comment]
What is the way to specifically target Firefox via the CLI to create a ZIP, in that case? I am not clear.

**Comment by aklinker1** [comment]
> What is the way to specifically target Firefox via the CLI to create a ZIP, in that case? I am not clear.

```sh
wxt zip -b firefox
```

- https://wxt.dev/guide/essentials/publishing.html#firefox-addon-store
- https://wxt.dev/api/cli/wxt-zip.html

**Comment by aklinker1** [comment]
> For the record, this command came from the "Get started" / Bootstrap area [here](https://wxt.dev/guide/installation.html).

"zip:firefox" is the package.json script WXT recommends you setup. You run it like so: `pnpm zip:firefox`. As you can see, it's just an alias for `wxt zip -b firefox`.

<img width="728" alt="Screenshot 2024-11-29 at 11 29 00 AM" src="https://github.com/user-attachments/assets/3f7780aa-649c-4424-8b7b-c91049b0bf04">

**Comment by joneslloyd** [comment]
Damn – my bad there! Thank you! 🙏
