### ISSUE TITLE
Build failure with `pnpm dev` using Vite 6.0.4 in WXT 0.19.22

### ISSUE THREAD

**Issue by only-issues** [wxt-dev/wxt#1293]
### Describe the bug

When running `pnpm dev` on a new project initialized with WXT 0.19.22, the build fails with multiple errors related to "Expected identifier but found 'import'". 

I noticed that the project automatically uses Vite 6.0.4, while my previous project using the same WXT version (0.19.22) worked perfectly with Vite 6.0.3. This version difference seems to be causing the issue, but I could not find a way to downgrade Vite to verify.

Full Error:
```
E:\NodeJs Projects\WXT\test-err>pnpm dev

> wxt-react-starter@0.0.0 dev E:\NodeJs Projects\WXT\test-err
> wxt


WXT 0.19.22                                                                                                   18:14:46
√ Started dev server @ http://localhost:3000                                                                  18:14:47
i Pre-rendering chrome-mv3 for development with Vite 6.0.4                                                    18:14:47
x Build failed in 48ms

 ERROR  [vite:define] Transform failed with 18 errors:                                                        18:14:48
(define name):1:0: ERROR: Expected identifier but found "import"
(define name):1:0: ERROR: Expected identifier but found "import"
(define name):1:0: ERROR: Expected identifier but found "import"
(define name):1:0: ERROR: Expected identifier but found "import"
(define name):1:0: ERROR: Expected identifier but found "import"
...
file: virtual:wxt-background-entrypoint?E:/NodeJs Projects/WXT/test-err/entrypoints/background.ts

    (define name):1:0: ERROR: Expected identifier but found "import"
    (define name):1:0: ERROR: Expected identifier but found "import"
    (define name):1:0: ERROR: Expected identifier but found "import"
    (define name):1:0: ERROR: Expected identifier but found "import"
    (define name):1:0: ERROR: Expected identifier but found "import"
    ...
    file: virtual:wxt-background-entrypoint?E:/NodeJs Projects/WXT/test-err/entrypoints/background.ts
    at failureErrorWithLog (node_modules\.pnpm\esbuild@0.24.1\node_modules\esbuild\lib\main.js:1476:15)
    at node_modules\.pnpm\esbuild@0.24.1\node_modules\esbuild\lib\main.js:755:50
    at responseCallbacks.<computed> (node_modules\.pnpm\esbuild@0.24.1\node_modules\esbuild\lib\main.js:622:9)
    at handleIncomingPacket (node_modules\.pnpm\esbuild@0.24.1\node_modules\esbuild\lib\main.js:677:12)
    at Socket.readFromStdout (node_modules\.pnpm\esbuild@0.24.1\node_modules\esbuild\lib\main.js:600:7)
    at Socket.emit (node:events:524:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Socket.Readable.push (node:internal/streams/readable:392:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:189:23)

× Command failed after 1.606 s                                                                                18:14:48

 ERROR  Failed to build background                                                                            18:14:48

    at buildEntrypoints (/E:/NodeJs%20Projects/WXT/test-err/node_modules/.pnpm/wxt@0.19.22_@types+node@22.10.2_rollup@4.28.1/node_modules/wxt/dist/core/utils/building/build-entrypoints.mjs:19:13)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at rebuild (/E:/NodeJs%20Projects/WXT/test-err/node_modules/.pnpm/wxt@0.19.22_@types+node@22.10.2_rollup@4.28.1/node_modules/wxt/dist/core/utils/building/rebuild.mjs:15:21)
    at internalBuild (/E:/NodeJs%20Projects/WXT/test-err/node_modules/.pnpm/wxt@0.19.22_@types+node@22.10.2_rollup@4.28.1/node_modules/wxt/dist/core/utils/building/internal-build.mjs:43:32)
    at buildAndOpenBrowser (/E:/NodeJs%20Projects/WXT/test-err/node_modules/.pnpm/wxt@0.19.22_@types+node@22.10.2_rollup@4.28.1/node_modules/wxt/dist/core/create-server.mjs:119:28)
    at Object.start (/E:/NodeJs%20Projects/WXT/test-err/node_modules/.pnpm/wxt@0.19.22_@types+node@22.10.2_rollup@4.28.1/node_modules/wxt/dist/core/create-server.mjs:75:7)
    at /E:/NodeJs%20Projects/WXT/test-err/node_modules/.pnpm/wxt@0.19.22_@types+node@22.10.2_rollup@4.28.1/node_modules/wxt/dist/cli/commands.mjs:32:5
    at CAC.<anonymous> (/E:/NodeJs%20Projects/WXT/test-err/node_modules/.pnpm/wxt@0.19.22_@types+node@22.10.2_rollup@4.28.1/node_modules/wxt/dist/cli/cli-utils.mjs:17:22)
    at /E:/NodeJs%20Projects/WXT/test-err/node_modules/.pnpm/wxt@0.19.22_@types+node@22.10.2_rollup@4.28.1/node_modules/wxt/dist/cli/index.mjs:11:1

  [cause]: [vite:define] Transform failed with 18 errors:
(define name):1:0: ERROR: Expected identifier but found "import"
(define name):1:0: ERROR: Expected identifier but found "import"
(define name):1:0: ERROR: Expected identifier but found "import"
(define name):1:0: ERROR: Expected identifier but found "import"
(define name):1:0: ERROR: Expected identifier but found "import"
...
file: virtual:wxt-background-entrypoint?E:/NodeJs Projects/WXT/test-err/entrypoints/background.ts

      (define name):1:0: ERROR: Expected identifier but found "import"
      (define name):1:0: ERROR: Expected identifier but found "import"
      (define name):1:0: ERROR: Expected identifier but found "import"
      (define name):1:0: ERROR: Expected identifier but found "import"
      (define name):1:0: ERROR: Expected identifier but found "import"
      ...
      file: virtual:wxt-background-entrypoint?E:/NodeJs Projects/WXT/test-err/entrypoints/background.ts
      at failureErrorWithLog (node_modules\.pnpm\esbuild@0.24.1\node_modules\esbuild\lib\main.js:1476:15)
      at node_modules\.pnpm\esbuild@0.24.1\node_modules\esbuild\lib\main.js:755:50
      at responseCallbacks.<computed> (node_modules\.pnpm\esbuild@0.24.1\node_modules\esbuild\lib\main.js:622:9)
      at handleIncomingPacket (node_modules\.pnpm\esbuild@0.24.1\node_modules\esbuild\lib\main.js:677:12)
      at Socket.readFromStdout (node_modules\.pnpm\esbuild@0.24.1\node_modules\esbuild\lib\main.js:600:7)
      at Socket.emit (node:events:524:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Socket.Readable.push (node:internal/streams/readable:392:5)
      at Pipe.onStreamRead (node:internal/stream_base_commons:189:23)

 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction

[test-err.zip](https://github.com/user-attachments/files/18210185/test-err.zip)

### Steps to reproduce

1. Run `pnpm dlx wxt@latest init`.
   - Choose the following options:
     - Template: React
     - Package Manager: pnpm
2. Change directory into the new project folder: `cd <project-name>`.
3. Install dependencies: `pnpm install`.
4. Start the development server: `pnpm dev`.

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
    Memory: 24.45 GB / 31.84 GB
  Binaries:
    Node: 22.12.0 - D:\nodejs\node.EXE
    npm: 10.9.0 - D:\nodejs\npm.CMD
    pnpm: 9.15.1 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (131.0.2903.86)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    wxt: ^0.19.13 => 0.19.22
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aiktb** [comment]
After adding the following code in package.json, it still fails:
```json
  "pnpm": {
    "overrides": {
      "vite": "6.0.3"
    }
  },
```

So it shouldn't be 6.0.4 that breaks this.

**Comment by aklinker1** [comment]
Seeing this on PR checks: https://github.com/wxt-dev/wxt/pull/1292#issuecomment-2556342291

**Comment by only-issues** [comment]
@aklinker1 @aiktb Today I tried deleting `node_modules` and `pnpm-lock.yaml` and reinstalling packages, then I saw it using vite version `6.0.5` and it worked without any errors.

**Comment by aiktb** [comment]
> @aklinker1 @aiktb Today I tried deleting `node_modules` and `pnpm-lock.yaml` and reinstalling packages, then I saw it using vite version `6.0.5` and it worked without any errors.

I reviewed the change log for vite @6.0.5, this is a regression issue for esbuild and has been resolved

**Comment by aklinker1** [comment]
Awesome, thanks for the update. Good to know it's not something I broke lol
