### ISSUE TITLE
Support setting `entrypointsDir` to `srcDir`

### ISSUE THREAD

**Issue by aklinker1** [wxt-dev/wxt#213]
> Originally suggested in https://github.com/wxt-dev/wxt/issues/192#issuecomment-1792951108 by @molvqingtai

To support project structures like this:

```
src/
  assets/
  content-script/
  opitons/
  devtools/
  ...
```

You need to be able to set `entrypointsDir` to `"."`.

```ts
// wxt.config.ts
export default defineConfig({
  srcDir: "src",
  entrypointsDir: ".",
});
```

Right now, Vite throws a vague error setting this config inside the vanilla template after moving all the files to the desired directories.

```
$ pnpm build

> wxt-starter@0.0.0 build /Users/aklinker1/Development/local/wxt-vanilla-no-entrypoints
> wxt build


WXT 0.8.7                                                                                                              12:48:57 PM
ℹ Building chrome-mv3 for production with Vite 4.5.0                                                                  12:48:57 PM
[vite]: Rollup failed to resolve import "/wxt.svg" from "/Users/aklinker1/Development/local/wxt-vanilla-no-entrypoints/src/popup/main.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
✖ Command failed after 1.621 s                                                                                        12:48:59 PM

[12:48:59 PM]  ERROR  [vite]: Rollup failed to resolve import "/wxt.svg" from "/Users/aklinker1/Development/local/wxt-vanilla-no-entrypoints/src/popup/main.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
build.rollupOptions.external

  This is most likely unintended because it can break your application at runtime.
  If you do want to externalize this module explicitly add it to
  build.rollupOptions.external
  at viteWarn (node_modules/.pnpm/vite@4.5.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:48216:27)
  at onRollupWarning (node_modules/.pnpm/vite@4.5.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:48248:9)
  at onwarn (node_modules/.pnpm/vite@4.5.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:47976:13)
  at node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:24276:13
  at Object.logger [as onLog] (node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25950:9)
  at ModuleLoader.handleInvalidResolvedId (node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:24862:26)
  at node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:24822:26

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by aklinker1** [comment]
Looking for someone to contribute this feature.

**Comment by dvlden** [comment]
I mean, it would just work, if you move `public` directory out of the `src`.

**Comment by aklinker1** [comment]
Can confirm, this works:

```ts
import { defineConfig } from "wxt";
import path from "node:path";

// See https://wxt.dev/api/config.html
export default defineConfig({
  srcDir: path.resolve("src"),
  entrypointsDir: path.resolve("src"),
  publicDir: path.resolve("public"),
});
```
