### ISSUE TITLE
Multiple "index" files in a entrypoint directory

### ISSUE THREAD

**Issue by aklinker1** [wxt-dev/wxt#275]
### Describe the bug

When you have two `index.*` files inside an entrypoint directory, like the Solid template, WXT will fail to build the application.

```
entrypoints/
  popup/
    index.html
    index.ts
    ...
```

WXT should not allow more than 1 entrypoint in a directory.

### Expected behavior

In this case, I'd either:

1. Only expect the HTML file to be counted as an entrypoint, and the `index.ts` file would be ignored.
2. Expect to be told I can't have two `index` files in a directory
   - Perhaps we need to move the "no duplicate entrypoint name" validation up before we import the files to grab their config.

### Screenshots

Here is one such failure:

```
[log] WXT 0.11.1
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
[info] Building chrome-mv3 for production with Vite 5.0.8
Error:  Cannot find module 'react/jsx-runtime'
Require stack:
- /home/runner/work/wxt/wxt/templates/solid/entrypoints/popup/index.tsx
  Require stack:
  - entrypoints/popup/index.tsx
  at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
  at Function.resolve (node:internal/modules/helpers:188:19)
  at _resolve (node_modules/jiti/dist/jiti.js:1:251148)
  at jiti (node_modules/jiti/dist/jiti.js:1:253746)
  at entrypoints/popup/index.tsx:1:88
  at evalModule (node_modules/jiti/dist/jiti.js:1:256443)
  at jiti (node_modules/jiti/dist/jiti.js:1:254371)
  at importEntrypointFile (node_modules/wxt/dist/cli.cjs:4163:23)
  at async getUnlistedScriptEntrypoint (node_modules/wxt/dist/cli.cjs:2798:25)
  at async node_modules/wxt/dist/cli.cjs:2648:18
Error:  Cannot find module 'react/jsx-runtime'
[fail] Command failed after 642 ms
Require stack:
- /home/runner/work/wxt/wxt/templates/solid/entrypoints/popup/index.tsx
  Require stack:
  - entrypoints/popup/index.tsx
  at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
  at Function.resolve (node:internal/modules/helpers:188:19)
  at _resolve (node_modules/jiti/dist/jiti.js:1:251148)
  at jiti (node_modules/jiti/dist/jiti.js:1:253746)
  at entrypoints/popup/index.tsx:1:88
  at evalModule (node_modules/jiti/dist/jiti.js:1:256443)
  at jiti (node_modules/jiti/dist/jiti.js:1:254371)
  at importEntrypointFile (node_modules/wxt/dist/cli.cjs:4163:23)
  at async getUnlistedScriptEntrypoint (node_modules/wxt/dist/cli.cjs:2798:25)
  at async node_modules/wxt/dist/cli.cjs:2648:18
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

### Environment

```
  System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 3.11 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.asdf/installs/nodejs/18.16.1/bin/node
    npm: 9.5.1 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.6.3 - ~/.asdf/installs/nodejs/18.16.1/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.71
    Safari: 16.5.2
  npmPackages:
    wxt: ^0.11.0 => 0.11.1 
```

### Additional context

Discovered while working on #274.

**Comment by aklinker1** [comment]
Release in [v0.11.2](https://github.com/wxt-dev/wxt/releases/tag/v0.11.2)
