### ISSUE TITLE
Remove Vite 5 CJS warning

### ISSUE THREAD

**Issue by aklinker1** [wxt-dev/wxt#277]
### Describe the bug

Vite 5 dropped CJS support, and are now showing a warning when importing the library into CJS.

```
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
```

I thought I already fixed this by using a dynamic import statement, but it still shows up... ~~Maybe I need to replace more of these:~~

```diff
- import * as vite from 'vite';
+ import type * as vite from 'vite';
```

Still showing up. We can always hide the error by setting the env variable `VITE_CJS_IGNORE_WARNING=true`.

### To Reproduce

The templates all report this error in CI: https://github.com/wxt-dev/wxt/actions/runs/7186289489/job/19571360231

### Expected behavior

The warning should not appear.

### Environment

N/A - see CI

### Additional context

Noticed here: https://github.com/wxt-dev/wxt/issues/270#issuecomment-1851129300

**Comment by aklinker1** [comment]
These are caused by plugins, not by WXT.

<img width="1041" alt="Screeshot of workflow, see text below" src="https://github.com/wxt-dev/wxt/assets/10101283/16e612d4-053d-4716-9b10-c1a23dd8c52d">

```
Trace: The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
    at warnCjsUsage (/home/runner/work/wxt/wxt/templates/vue/node_modules/vite/index.cjs:32:3)
    at Object.<anonymous> (/home/runner/work/wxt/wxt/templates/vue/node_modules/vite/index.cjs:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/runner/work/wxt/wxt/templates/vue/node_modules/@vitejs/plugin-vue/dist/index.cjs:6:14)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
```

**Comment by aklinker1** [comment]
If you want to figure out what's causing this warning in your project, run the following:

```sh
VITE_CJS_TRACE=true wxt build
```

**Comment by aklinker1** [comment]
Actually, this appears to be WXT's fault. It's loading the wxt.config.ts file, and importing the CJS versions of the vite plugins, instead of the ESM versions. So it's likely `c12` or `jiti` causing the warning.

**Comment by aklinker1** [comment]
Checking out Vite's code, they litterally just use a dyamic import to load the config file: 

https://github.com/vitejs/vite/blob/5684fcd8d27110d098b3e1c19d851f44251588f1/packages/vite/src/node/config.ts#L1180

We could try that instead of relying on `c12` to load the file and modules as ESM.

**Comment by aklinker1** [comment]
I'm going to close this and open a new issue now that I know what the problem is.

**Comment by aklinker1** [comment]
The warning goes away if I remove jiti from the project - `c12` and `jiti`.
