### ISSUE TITLE
Cannot load templates

### ISSUE THREAD

**Issue by asasas234** [wxt-dev/wxt#315]
When I use the following command to initialize a project, an error occurs.
```
pnpx wxt@latest init test-wtx-plugin
```
The error is as follows.
```

Packages: +377
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 411, reused 186, downloaded 191, added 377, done
../Library/pnpm/store/v3/tmp/dlx-35362/node_modules/.pnpm/spawn-sync@1.0.15/node_modules/spawn-sync: Running postinstall script, done in 39ms
../Library/pnpm/store/v3/tmp/dlx-35362/node_modules/.pnpm/dtrace-provider@0.8.8/node_modules/dtrace-provider: Running install script, done in 2.9s
../Library/pnpm/store/v3/tmp/dlx-35362/node_modules/.pnpm/esbuild@0.19.11/node_modules/esbuild: Running postinstall script, done in 475ms

WXT 0.13.1                                                                                                                                                                                           10:27:40 PM
ℹ Initalizing new project                                                                                                                                                                           10:27:40 PM
✖ Command failed after 409 ms                                                                                                                                                                       10:27:40 PM

 ERROR  Cannot load templates: {}                                                                                                                                                                    10:27:40 PM

  at listTemplates (/Users/lizhibo/Library/pnpm/store/v3/tmp/dlx-35362/node_modules/.pnpm/wxt@0.13.1/node_modules/wxt/dist/cli.js:2915:11)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async initialize (/Users/lizhibo/Library/pnpm/store/v3/tmp/dlx-35362/node_modules/.pnpm/wxt@0.13.1/node_modules/wxt/dist/cli.js:2835:21)
  at async cli.command.option.option.action.wrapAction.disableFinishedLog (/Users/lizhibo/Library/pnpm/store/v3/tmp/dlx-35362/node_modules/.pnpm/wxt@0.13.1/node_modules/wxt/dist/cli.js:3082:7)
  at async CAC.<anonymous> (/Users/lizhibo/Library/pnpm/store/v3/tmp/dlx-35362/node_modules/.pnpm/wxt@0.13.1/node_modules/wxt/dist/cli.js:3101:22)

```

**Comment by aklinker1** [comment]
I have seen this happen in the past as well, the request to the API listing the folders in the `templates` folder sometimes fails. GitHub has had lots of outages, and this is one downside to hosting the templates instead of shipping them with the NPM package.

I just ran the command now, and it's working again. I'm not sure if a backoff/retry would help in this case, but the error message could be improved for sure.

https://github.com/wxt-dev/wxt/blob/bdce363eed0b51a8a6f1dc3c066e2b5c9f1f5835/src/core/initialize.ts#L91-L123

I don't know why I chose to `JSON.stringify` the error... I should have used [`cause`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error#cause).

**Comment by asasas234** [comment]
@aklinker1 Thank you very much. I tried to run it again and it's all good now.

**Comment by jtsang4** [comment]
I encountered the same problem and tried many times it is still not working.

**Comment by aklinker1** [comment]
Here's the network request used to fetch the list of templates:

```sh
curl -v https://api.github.com/repos/wxt-dev/wxt/contents/templates -H Accept:application/vnd.github+json -H 
X-GitHub-Api-Version:2022-11-28
```

If you encounter an error, please run this command and share the output so I can debug.

**Comment by jtsang4** [comment]
@aklinker1 After run this curl command, I got error output:
```
{"message":"API rate limit exceeded for <IP>. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
* Connection #0 to host api.github.com left intact
```

But after I tried `bunx --bun wxt@latest init test-ext` it works, maybe the only way is try more times if not want to use Authenticated requests.

**Comment by aklinker1** [comment]
Ahh rate limits. We can improve that using ungh:

https://unjs.io/packages/ungh#reposownernamefilesbranchpath
