### ISSUE TITLE
[vite-plugin-vue-devtools] Vue Devtools support

### ISSUE THREAD

**Issue by mattstrayer** [wxt-dev/wxt#533]
### Feature Request

Is it possible to integrate [vue-devtools-next](https://github.com/vuejs/devtools-next) as a vite plugin. Neither that nor the vue devtools chrome extension recognize that I'm using a vue app.

#### Is your feature request related to a bug?

N/A

**Comment by aklinker1** [comment]
For now, use the standalone app:

https://devtools-next.vuejs.org/guide/standalone

**Comment by pavitra-infocusp** [comment]
https://github.com/vuejs/devtools-next/issues/436

I'm interested in getting the Vue devtools plugin to work. How to do I get started? @aklinker1

**Comment by aklinker1** [comment]
@pavitra-infocusp just try using it on an extension with only a popup. I kinda expect it to work in this case. It definitely won't work for content scripts.

The big thing WXT does to enable dev mode is change URLs from `/abc` to the dev server's full URL, `http://localhost:3000/abc`. Vite assumes you're loading files from the server, so it uses absolute paths. WXT has to load scripts from the files in the output directory, so all URLs need to be updated.

So you may need to use a custom vite plugin to transform additional URLs injected by the dev tools plugin.

**Comment by alexzhang1030** [comment]
```ts
// wxt.config.ts
import { defineConfig } from 'wxt'
import vue from '@vitejs/plugin-vue'
import devtools from 'vite-plugin-vue-devtools'

export default defineConfig({
  vite: () => ({
    plugins: [
      vue(),
      devtools({
        // your app entrypoint (wherever you call createApp())
        appendTo: '/entrypoints/popup/main.ts',
      }),
    ],
  }),
})
```

**Comment by aklinker1** [comment]
Since we have a working solution, I'm gonna close this issue!

**Comment by mattstrayer** [comment]
This now seems to be broken with the latest versions. 


```typescript
import { defineConfig } from "wxt";
import devtools from "vite-plugin-vue-devtools";

// See https://wxt.dev/api/config.html
export default defineConfig({
  modules: ["@wxt-dev/module-vue", "@wxt-dev/auto-icons"],

  srcDir: "src",

  manifest: {
    name: "mindful - stay focused on your goals",
    description: "Stay present, focused, and intentional each day.",
    permissions: ["tabs", "storage"],
  },

  vite: () => ({
    plugins: [
      devtools({
        // your app entrypoint (wherever you call createApp())
        appendTo: "/entrypoints/newtab/main.ts",
      }),
      devtools({
        // your app entrypoint (wherever you call createApp())
        appendTo: "/entrypoints/popup/main.ts",
      }),
    ],
  }),
});
```


### Output 

```
❯ npm i

> mindful@1.0.3 postinstall
> wxt prepare


WXT 0.19.2                                                                                                                                  1:04:04 PM
ℹ Generating types...                                                                                                                      1:04:05 PM
✖ Command failed after 501 ms                                                                                                              1:04:05 PM

 ERROR  Invalid URL                                                                                                                         1:04:05 PM

  at new URL (node:internal/url:797:36)
  at getVueDevtoolsPath (node_modules/vite-plugin-vue-devtools/dist/vite.cjs:7996:231)
  at VitePluginVueDevTools (node_modules/vite-plugin-vue-devtools/dist/vite.cjs:8017:27)
  at Object.vite (wxt.config.ts:18:40)
  at vite (node_modules/wxt/dist/core/utils/building/resolve-config.mjs:312:59)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async wxt2.config.vite (node_modules/wxt/dist/modules.mjs:30:24)
  at async wxt2.config.vite (node_modules/wxt/dist/modules.mjs:30:24)
  at async getBaseConfig (node_modules/wxt/dist/core/builders/vite/index.mjs:15:20)
  at async Object.importEntrypoint (node_modules/wxt/dist/core/builders/vite/index.mjs:168:30)
  at async getBackgroundEntrypoint (node_modules/wxt/dist/core/utils/building/find-entrypoints.mjs:255:27)
  at async node_modules/wxt/dist/core/utils/building/find-entrypoints.mjs:58:20
  at async Promise.all (index 0)
  at async Object.run (node_modules/wxt/dist/core/utils/environments/environment.mjs:13:14)
  at async findEntrypoints (node_modules/wxt/dist/core/utils/building/find-entrypoints.mjs:45:23)
  at async prepare (node_modules/wxt/dist/core/prepare.mjs:6:23)
  at async node_modules/wxt/dist/cli/commands.mjs:73:5
  at async CAC.<anonymous> (node_modules/wxt/dist/cli/cli-utils.mjs:16:22)
  at async node_modules/wxt/dist/cli/index.mjs:11:1

npm error code 1
npm error path /Users/matt/dev/mindful
npm error command failed
npm error command sh -c wxt prepare

npm error A complete log of this run can be found in: /Users/matt/.npm/_logs/2024-07-28T17_04_03_993Z-debug-0.log
```


Output log file attached

[2024-07-28T17_04_03_993Z-debug-0.log](https://github.com/user-attachments/files/16404603/2024-07-28T17_04_03_993Z-debug-0.log)

**Comment by mattstrayer** [comment]
FYI  -- This works with 0.19.0, but breaks when moving to 0.19.1

@aklinker1

**Comment by alexzhang1030** [comment]
Related https://github.com/wxt-dev/wxt/commit/c8ddc66cfad5a25039917c3b56699d84a4bc952d, you can use `entrypointLoader: 'jiti` for a temporal workaround.

```ts
export default defineConfig({
  entrypointLoader: "jiti",
  modules: ["@wxt-dev/module-vue"],
  vite: () => ({
    plugins: [
      devtools({
        appendTo: "/entrypoints/popup/main.ts",
      }),
    ],
  }),
});
```

**Comment by alexzhang1030** [comment]
It’s not entirely clear whether the issue is related to ‘wxt’ or something else. The root cause is:

<img width="931" alt="image" src="https://github.com/user-attachments/assets/7bf315ba-fa8e-4503-878f-f9c21b7cfaa7">

`document` was set to `null` by someone, which makes `typeof document === 'undefined'` evaluate to true, but it raises an error when executing `new URL('vite.cjs', null)`.

**Comment by mattstrayer** [comment]
Adding the entrypointloader as you suggested worked for now! Thank you! @alexzhang1030 

Vscode is showing that as a deprecated field, is that correct?

**Comment by alexzhang1030** [comment]
> Adding the entrypointloader as you suggested worked for now! Thank you! @alexzhang1030
> 
> Vscode is showing that as a deprecated field, is that correct?

As it's a temporal workaround, you can use it until wxt remove it. we should discuss how to resolve it.

**Comment by aklinker1** [comment]
Likely the problem is that we shouldn't use `vite-plugin-vue-devtools` when importing entrypoints. By default, all plugins are passed into `vite-node`.

As an alternative, you could add the plugin in the following hooks: 
- https://wxt.dev/api/reference/wxt/interfaces/WxtHooks.html#vite-devserver-extendconfig
- https://wxt.dev/api/reference/wxt/interfaces/WxtHooks.html#vite-build-extendconfig

If you'd like, it might make sense to add devtools to the `@wxt-dev/module-vue`, and it could abstract away adding the plugin in those two hooks.

**Comment by alexzhang1030** [comment]
> Likely the problem is that we shouldn't use `vite-plugin-vue-devtools` when importing entrypoints. By default, all plugins are passed into `vite-node`. See ["Entrypoint Loader"](https://wxt.dev/guide/go-further/entrypoint-loaders.html) docs for more details about them.
> 
> As an alternative, you could add the plugin in the following hooks:
> 
> * [wxt.dev/api/reference/wxt/interfaces/WxtHooks.html#vite-devserver-extendconfig](https://wxt.dev/api/reference/wxt/interfaces/WxtHooks.html#vite-devserver-extendconfig)
> * [wxt.dev/api/reference/wxt/interfaces/WxtHooks.html#vite-build-extendconfig](https://wxt.dev/api/reference/wxt/interfaces/WxtHooks.html#vite-build-extendconfig)
> 
> ```ts
> export default defineConfig({
>   hooks: {
>     'vite:devServer:extendConfig': (config) => {
>       config.plugins.push(devtools(...))
>     },
>     'vite:build:extendConfig ': (config) => {
>       config.plugins.push(devtools(...))
>     },
>   },
> });
> ```
> 
> If you'd like, it might make sense to add devtools to the `@wxt-dev/module-vue`, and it could abstract away adding the plugin in those two hooks. But I'd prefer to not do this until it's stable :/

The root reason is that `document` should not be null, it has some fallbacks on `node` env or `browser` env, so vite or vite-node   should both work properly.

**Comment by marijnbent** [comment]
<img width="409" alt="Image" src="https://github.com/user-attachments/assets/942a229d-5a3b-4dd2-b11f-6a5a7ee43c54" />

This doesn't work for me. `Cannot read properties of undefined (reading 'push')`.

Would be nice to add this in @wxt-dev/module-vue!

**Comment by aiktb** [comment]
> It’s not entirely clear whether the issue is related to ‘wxt’ or something else. The root cause is:
> 
> <img alt="image" width="931" src="https://private-user-images.githubusercontent.com/49969959/353678248-7bf315ba-fa8e-4503-878f-f9c21b7cfaa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDc4ODA4ODMsIm5iZiI6MTc0Nzg4MDU4MywicGF0aCI6Ii80OTk2OTk1OS8zNTM2NzgyNDgtN2JmMzE1YmEtZmE4ZS00NTAzLTg3OGYtZjljMjFiN2NmYWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTIyVDAyMjMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjZjQ4ODc4MTRmNjUwMzNmODg0MDcxNTM4MWQ2ZmMwNGNjYWRlYWM4YWFiYjk4OTZiZGI3NjI1ZjhmY2Y4ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lDNYj7yVUMjPYP9IbR-6ox4jUAnB5diOKusUrA0bg_I">
> `document` was set to `null` by someone, which makes `typeof document === 'undefined'` evaluate to false, but it raises an error when executing `new URL('vite.cjs', null)`.

This error has disappeared in WXT 0.20.6. It is no longer necessary to use the WXT `vite:devServer:extendConfig` hook to introduce the plugin. Directly introducing the plugin works fine.
