### ISSUE TITLE
browser.action.onClicked.addListener not implemented?

### ISSUE THREAD

**Issue by Eyalm321** [wxt-dev/wxt#669]
ERROR  Browser.action.onClicked.addListener not implemented.                                                                                                                                         3:37:44 AM  

Mock the function yourself using your testing framework, or submit a PR with an in-memory implementation.

  Mock the function yourself using your testing framework, or submit a PR with an in-memory implementation.
  at Object.addListener (node_modules\@webext-core\fake-browser\lib\index.cjs:996:15)
  at C:/Users/Admin/CallCenterAgentOrchestrationPlatform/google-extension-research/my-port/example-wxt/entrypoints/background.ts:2:41
  at evalModule (node_modules\jiti\dist\jiti.js:1:256443)
  at jiti (node_modules\jiti\dist\jiti.js:1:254371)
  at importEntrypointFile (/C:/Users/Admin/CallCenterAgentOrchestrationPlatform/google-extension-research/my-port/example-wxt/node_modules/wxt/dist/cli.js:2278:23)
  at async getBackgroundEntrypoint (/C:/Users/Admin/CallCenterAgentOrchestrationPlatform/google-extension-research/my-port/example-wxt/node_modules/wxt/dist/cli.js:1502:27)
  at async /C:/Users/Admin/CallCenterAgentOrchestrationPlatform/google-extension-research/my-port/example-wxt/node_modules/wxt/dist/cli.js:1306:18
  at async Promise.all (index 0)
  at async findEntrypoints (/C:/Users/Admin/CallCenterAgentOrchestrationPlatform/google-extension-research/my-port/example-wxt/node_modules/wxt/dist/cli.js:1294:23)
  at async internalBuild (/C:/Users/Admin/CallCenterAgentOrchestrationPlatform/google-extension-research/my-port/example-wxt/node_modules/wxt/dist/cli.js:3165:23)

✖ Command failed after 1.075 s                                                                                                                                                                       3:37:44 AM

 ERROR  Failed to load entrypoint: entrypoints\background.ts                                                                                                                                          3:37:44 AM  

  at importEntrypointFile (/C:/Users/Admin/CallCenterAgentOrchestrationPlatform/google-extension-research/my-port/example-wxt/node_modules/wxt/dist/cli.js:2290:13)
  at async getBackgroundEntrypoint (/C:/Users/Admin/CallCenterAgentOrchestrationPlatform/google-extension-research/my-port/example-wxt/node_modules/wxt/dist/cli.js:1502:27)
  at async /C:/Users/Admin/CallCenterAgentOrchestrationPlatform/google-extension-research/my-port/example-wxt/node_modules/wxt/dist/cli.js:1306:18
  at async Promise.all (index 0)
  at async findEntrypoints (/C:/Users/Admin/CallCenterAgentOrchestrationPlatform/google-extension-research/my-port/example-wxt/node_modules/wxt/dist/cli.js:1294:23)
  at async internalBuild (/C:/Users/Admin/CallCenterAgentOrchestrationPlatform/google-extension-research/my-port/example-wxt/node_modules/wxt/dist/cli.js:3165:23)
  at async buildAndOpenBrowser (/C:/Users/Admin/CallCenterAgentOrchestrationPlatform/google-extension-research/my-port/example-wxt/node_modules/wxt/dist/cli.js:3494:28)
  at async Object.start (/C:/Users/Admin/CallCenterAgentOrchestrationPlatform/google-extension-research/my-port/example-wxt/node_modules/wxt/dist/cli.js:3459:9)
  at async /C:/Users/Admin/CallCenterAgentOrchestrationPlatform/google-extension-research/my-port/example-wxt/node_modules/wxt/dist/cli.js:3980:5
  at async CAC.<anonymous> (/C:/Users/Admin/CallCenterAgentOrchestrationPlatform/google-extension-research/my-port/example-wxt/node_modules/wxt/dist/cli.js:3911:22)

import { PublicPath, browser } from 'wxt/browser';

browser.action.onClicked.addListener((tab) => {
  browser.windows.create({
    url: browser.runtime.getURL("popup.html" as PublicPath),
    type: "popup",
    width: 400,
    height: 600,
    left: 10,
    top: 10
  });
});

Please implement, thanks.

**Comment by Eyalm321** [comment]
Appreciate you!

**Comment by mundane799699** [comment]
I want to achieve the following effect: when I click on the plugin icon in the extension toolbar, instead of opening a popup page, it should open a new tab and load sync.html, which I have defined myself. How can I do this? I tried deleting the popup directory, but then the plugin icon was disabled.

**Comment by aiktb** [comment]
> I want to achieve the following effect: when I click on the plugin icon in the extension toolbar, instead of opening a popup page, it should open a new tab and load sync.html, which I have defined myself. How can I do this? I tried deleting the popup directory, but then the plugin icon was disabled.

The `action` key in `manifest.json` is necessary for this, otherwise the extension will not be able to access the `chrome.action` API.
This will throw an uncaught Error at the top level of the background, which is why your extension is disabled.

`wxt.config.ts` solution:

```ts
import { defineConfig } from "wxt";

export default defineConfig({
  manifest: {
    action: {},
  },
});
```

**Comment by mundane799699** [comment]
> > > I want to achieve the following effect: when I click on the plugin icon in the extension toolbar, instead of opening a popup page, it should open a new tab and load sync.html, which I have defined myself. How can I do this? I tried deleting the popup directory, but then the plugin icon was disabled.
> > 
> > 
> > https://developer.chrome.com/docs/extensions/reference/api/action#manifest
> > The `action` key in `manifest.json` is necessary for this, otherwise the extension will not be able to access the `chrome.action` API. This will throw an uncaught Error at the top level of the background, which is why your extension is disabled.
> > `wxt.config.ts` solution:
> > ```ts
> > import { defineConfig } from "wxt";
> > 
> > export default defineConfig({
> >   manifest: {
> >     action: {},
> >   },
> > });
> > ```
> 
> thanks a lot.I found this, [#612 (comment)](https://github.com/wxt-dev/wxt/issues/612#issuecomment-2053910746) so I renamed popup folder to popup-bak, and I modified wxt.config.ts like this:
> 
> ```
> import { defineConfig } from "wxt";
> 
> // See https://wxt.dev/api/config.html
> export default defineConfig({
>   modules: ["@wxt-dev/module-react"],
>   manifest: {
>     permissions: ["tabs"],
>     action: {},
>   },
> });
> ```
> 
> then I modified background.ts like this:
> 
> ```
> export default defineBackground(() => {
>   console.log("Hello background!", { id: browser.runtime.id });
>   browser.action.onClicked.addListener(async () => {
>     await browser.tabs.create({ url: "/sync.html" });
>   });
> });
> ```
> 
> finally, it worked!!!

and I found when I delete the popup folder, it still work.so just add "action: {}" is ok.

**Comment by aklinker1** [comment]
https://wxt.dev/guide/key-concepts/manifest.html#action-without-popup
