### ISSUE TITLE
wxt zip ERROR

### ISSUE THREAD

**Issue by tesths** [wxt-dev/wxt#825]
### Describe the bug

Today when I use `wxt zip`
The error is
```
[10:44:25]  ERROR  [vite]: Rollup failed to resolve import "virtual:wxt-plugins" from "virtual:wxt-background?/Users/tesths/Desktop/test123/entrypoints/background.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
build.rollupOptions.external

  This is most likely unintended because it can break your application at runtime.
  If you do want to externalize this module explicitly add it to
  build.rollupOptions.external
  at viteWarn (/Users/tesths/Library/pnpm/global/5/.pnpm/vite@5.2.9_@types+node@14.18.33/node_modules/vite/dist/node/chunks/dep-_QLjGPdL.js:67601:27)
  at onRollupWarning (/Users/tesths/Library/pnpm/global/5/.pnpm/vite@5.2.9_@types+node@14.18.33/node_modules/vite/dist/node/chunks/dep-_QLjGPdL.js:67629:9)
```
And my folder structure is
```
prompts/
     assets/
     entrypoints/
       content/
           index.tsx
       options/
           index.html
           main.tsx
       popup/
           index.html
           main.tsx
   background.ts
```

I am sure when I use `pnpm run`, all things is run well.

### Reproduction

And then, I try to use `pnpm dlx wxt` new project, after run, there is still error like
```
[10:44:25]  ERROR  [vite]: Rollup failed to resolve import "virtual:wxt-plugins" from "virtual:wxt-background?/Users/tesths/Desktop/test123/entrypoints/background.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
```

### System Info

```shell
(base) ➜  prompts git:(main) ✗ npx envinfo --system --browsers --binaries --npmPackages wxt,vite
Need to install the following packages:
  envinfo@7.13.0
Ok to proceed? (y) y

  System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 131.98 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    pnpm: 9.5.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5
  npmPackages:
    wxt: ^0.18.1 => 0.18.1
```
```


### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
Update WXT to the latest version.

**Comment by tesths** [comment]
Thank you vary much.
Everything is run well now.
I found what's wrong with me.
My global pnpm wxt version is 0.17.
Though I update wxt in my project to 0.18.14, but `wxt zip` use default global version.
