### ISSUE TITLE
Web Workers: "_<name> not defined"

### ISSUE THREAD

**Issue by aklinker1** [wxt-dev/wxt#942]
### Describe the bug

In the web-worker-setup example, the worker runs just fine, but at the end, it throws and error:

```
Uncaught ReferenceError: _content is not defined
    at worker.ts:1:32
    at worker.ts:1:32
```

This is because WXT is adding a return value to all IIFE files. Here's the base64 encoded worker file:

```
KGZ1bmN0aW9uKCkgewogICJ1c2Ugc3RyaWN0IjsKICBjb25zb2xlLmxvZygiSGVsbG8gZnJvbSB3b3JrZXIiKTsKICBfY29udGVudDsKfSkoKTsKX2NvbnRlbnQ7Ci8vIyBzb3VyY2VNYXBwaW5nVVJMPWRhdGE6YXBwbGljYXRpb24vanNvbjtjaGFyc2V0PXV0Zi04O2Jhc2U2NCxleUoyWlhKemFXOXVJam96TENKbWFXeGxJam9pZDI5eWEyVnlMVU5SZDBOQ05uQndMbXB6SWl3aWMyOTFjbU5sY3lJNld5SXVMaTlsYm5SeWVYQnZhVzUwY3k5amIyNTBaVzUwTDNkdmNtdGxjaTUwY3lKZExDSnpiM1Z5WTJWelEyOXVkR1Z1ZENJNld5SmpiMjV6YjJ4bExteHZaeWhjSWtobGJHeHZJR1p5YjIwZ2QyOXlhMlZ5WENJcE8xeHVJbDBzSW01aGJXVnpJanBiWFN3aWJXRndjR2x1WjNNaU9pSTdPMEZCUVVFc1ZVRkJVU3hKUVVGSkxHMUNRVUZ0UWpzN095SjkK
```

Here it is decoded.

```
(function() {
  "use strict";
  console.log("Hello from worker");
  _content;
})();
_content;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoid29ya2VyLUNRd0NCNnBwLmpzIiwic291cmNlcyI6WyIuLi9lbnRyeXBvaW50cy9jb250ZW50L3dvcmtlci50cyJdLCJzb3VyY2VzQ29udGVudCI6WyJjb25zb2xlLmxvZyhcIkhlbGxvIGZyb20gd29ya2VyXCIpO1xuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7O0FBQUEsVUFBUSxJQUFJLG1CQUFtQjs7OyJ9

```

In this case, because the worker is loaded from `entrypoints/content.ts`, the error is "_content not defined".

### Reproduction

https://github.com/wxt-dev/examples/tree/main/examples/web-worker-setup

### Steps to reproduce

pnpm dev

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 2.57 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.3 - ~/.asdf/installs/nodejs/18.20.3/bin/node
    npm: 10.7.0 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.15.8 - ~/.asdf/installs/nodejs/18.20.3/bin/pnpm
    bun: 1.1.22 - ~/.bun/bin/bun
  Browsers:
    Chrome: 128.0.6613.85
    Safari: 17.2.1
  npmPackages:
    wxt: ^0.18.6 => 0.18.15
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anhkind** [comment]
I got a similar error in the extension page: `Uncaught ReferenceError: content is not defined`. Really don't know why we have the entrypoint name 'content'  appended at the end of the script there.

**Comment by fkatsuhiro** [comment]
Hi, I try to reproduce this issue in my local. In current latest version, it might be already fixed this issue.....
If something miss from my side, could you give me more information about this?

### wxt - v0.20.5
Can reproduce this issue 

<img width="1170" height="698" alt="Image" src="https://github.com/user-attachments/assets/2f3730c4-40e6-4646-9513-f41ff5496e97" />

```
System:
    OS: macOS 15.5
    CPU: (10) arm64 Apple M4
    Memory: 225.13 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.7.0 - /opt/homebrew/bin/node
    npm: 11.5.1 - /opt/homebrew/bin/npm
    pnpm: 10.7.0 - /opt/homebrew/bin/pnpm
    bun: 1.3.14 - /Users/katsu/.bun/bin/bun
  Browsers:
    Chrome: 153.0.8010.36
    Safari: 18.5
  npmPackages:
    typescript: ^5.8.2 => 5.8.2 
    wxt: ^0.20.5 => 0.20.5 
```

### wxt - v0.21.4
Cannot reproduce this bug.

<img width="1169" height="677" alt="Image" src="https://github.com/user-attachments/assets/c61395b9-90ca-477c-a15d-ec7ce942f364" />

```
System:
    OS: macOS 15.5
    CPU: (10) arm64 Apple M4
    Memory: 838.00 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.7.0 - /opt/homebrew/bin/node
    npm: 11.5.1 - /opt/homebrew/bin/npm
    pnpm: 10.7.0 - /opt/homebrew/bin/pnpm
    bun: 1.3.14 - /Users/katsu/.bun/bin/bun
  Browsers:
    Chrome: 153.0.8010.36
    Safari: 18.5
  npmPackages:
    typescript: ^5.8.2 => 5.8.2 
    web-ext: ^10.6.0 => 10.6.0 
    wxt: ^0.21.4 => 0.21.4 
```
