### ISSUE TITLE
Submit command may not be respecting the HTTP_PROXY setting.

### ISSUE THREAD

**Issue by xxnuo** [wxt-dev/wxt#981]
### Describe the bug

Due to poor network conditions, I need to use a proxy to access Google.
However, during the refresh token process, I noticed that WXT does not adhere to the system's proxy-related settings including HTTP HTTPS ALL_PROXY.
Therefore, I am unable to use the submit command properly.

### Reproduction

On this opensource project

https://github.com/xxnuo/jizhi-mod/

### Steps to reproduce

```zsh

echo $HTTP_PROXY
http://127.0.0.1:7890

pnpm wxt submit init
ℹ Initialize or update an existing .env.submit file.                                                                           1:39:15 PM

...

✔ Generate new refresh token?
Yes
[1:39:24 PM] https://accounts.google.com/o/oauth2/auth?response_type=code&scope=xxxx

✔ Open the above URL, login, and enter the auth code:
xxx

 ERROR  [POST] "https://accounts.google.com/o/oauth2/token": <no response> fetch failed                                         1:40:04 PM

  at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  at async $fetch2 (node_modules/.pnpm/ofetch@1.3.4/node_modules/ofetch/dist/shared/ofetch.897a6909.cjs:274:15)
  at async initChrome (node_modules/.pnpm/publish-browser-extension@2.1.3/node_modules/publish-browser-extension/dist/cli.cjs:3614:17)
  at async init (node_modules/.pnpm/publish-browser-extension@2.1.3/node_modules/publish-browser-extension/dist/cli.cjs:3535:26)
  at async CAC.<anonymous> (node_modules/.pnpm/publish-browser-extension@2.1.3/node_modules/publish-browser-extension/dist/cli.cjs:3907:5)
```

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12600KF
    Memory: 34.56 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.8.0 - /usr/local/bin/node
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 9.10.0 - ~/Library/pnpm/pnpm
    bun: 1.1.27 - /usr/local/bin/bun
  Browsers:
    Chrome: 128.0.6613.138
    Safari: 17.5
  npmPackages:
    wxt: ^0.19.7 => 0.19.7
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
I know nothing about http proxies, how to set one up, or how to use them :/

If you're willing to contribute, the code is available at: https://github.com/aklinker1/publish-browser-extension

**Comment by xxnuo** [comment]
Alright, I'll give it a shot😂

**Comment by aklinker1** [comment]
Moving this issue to the upstream repo: https://github.com/aklinker1/publish-browser-extension/issues/35
